class DataBaseAdapter:
    def __init__(self, **kwargs):
        ...

    def get_client(self):
        ...

    def get_data(self, table_name, query):
        ...

    def get_datas(self, table_name, query):
        ...

    def create_data(self, table_name, data):
        ...

    def update_data(self, table_name, query, new_data):
        ...

    def delete_data(self, table_name, query):
        ...
